### ISSUE TITLE
Upgrading 7.5 to 7.6 Yum breaks Network and Local SR

### ISSUE THREAD

**Issue by eangulus** [xcp-ng/xcp#116]
Upgraded a Pool of 2x Cisco C210 Servers doing Master first.

Rebooted Master and it didn't come back, after attaching a console, found it had booted but with no NIC's and no local SR. I'm not doing anything out of the ordinary here either, have no 3rd party add-ons only ever ran 2 boxes with local and NFS storage. No HA or anything either.

Problem is now, I have a slave I can't get into because it asks for the master in the pool. I also have VM's on the master Local SR I need back up and running as well, and I don't want to do too much in case I lose my VM's.

I figure it should be able to be solved as it seems to have just lost the association to SR and NIC's and would like to simply restore the config it already has. The main issue is I can't roll back to 7.5 as I did a yum update not an ISO one (won't make that mistake again).

I don't mind getting my hands dirty in the CLI, but I am not experienced enough yet to be comfortable randomly trying stuff that may break my system further. In the 5 years I have run XS then XCP I have never had an issue like this before.

UPDATE: Noticed that on boot XCP reports that the CPU has no virtualization. That's wrong, it has and was working before and I verified that the virtualization features are turned on in the BIOS. Mentioning in case it means something as well.

UPDATE 2: In case it matters, I had upgraded the Pool Slave to 7.6 but hadn't yet rebooted or restarted the toolstack. I still have network access to it, and upon checking in the xsconsole, it too says there is no NIC's or SR's (local or remote). I do a network test, and it pings the www.kernel.org url fine. My guess is the moment I reboot this slave server or restart the toolstack it will no longer be accessible either.

**Comment by olivierlambert** [comment]
Hi there,

1. If you want community support, it would be better to post on XCP-ng forum, until people around there assisted you to get a more precise idea of what gone wrong here
2. FYI, the only thing I heard previously that was similar to your issue is a NIC driver issue. `dmesg` on the problematic master should help
3. If it's urgent and these are production hosts and you need remote assistance, you can consider getting [pro support](https://xcp-ng.com)

I'll keep the issue open, feel free to edit it when you have more details from the [community forum](https://xcp-ng.org/forum)

**Comment by olivierlambert** [comment]
I saw you did posted on the forum, great :) 

When you upgraded, did you strictly followed https://github.com/xcp-ng/xcp/wiki/Upgrade-Howto ? I'm concerned you maybe had the clustering enabled on your pool.

**Comment by stormi** [comment]
The problem was solved on the forum (https://xcp-ng.org/forum/topic/753/upgrade-xcp-ng-7-5-to-7-6-problems). Closing!
