### ISSUE TITLE
XenServer package re-branding rfc

### ISSUE THREAD

**Issue by gagomes** [xcp-ng/xcp#13]
# Purpose

Agree on a scheme for rebranding packages from xenserver/citrix to xcp-ng

# Problem

As we fork XenServer, we will need to re-brand components in order to avoid being involved in a legal suit for infringing the original copyright.

# Proposal

I would like to propose we approach the re-branding as follows:

For each package requiring re-brand (containing the words citrix or xenserver) we should:

1. create a corresponding github repo
2. import the source into this repo
3. tag each import in a way that it matches the version in the rpm source release (vanilla state)
4. Apply our re-branding changes

Thoughts from the core developers will be most appreciated, though we will gladly appreciate any feedback from the community as well.

**Comment by johnelse** [comment]
I think this looks sensible. If any of the relevant code already exists under https://github.com/xenserver we should fork those repos and add tags (if necessary).

**Comment by gagomes** [comment]
Good call on forking existing packages!

**Comment by stormi** [comment]
Actually, I think we shouldn't fork the repos unless we are really ready to maintain the forked versions, regularly merge from master, etc.

In most cases, we want to keep considering that https://github.com/xenserver is the upstream and use the same sources as XenServer, with little changes if any at all.

In those cases, we need to apply our changes as patches during the RPM build. In the end, we do have one git repository per package as suggested, but they are structured like source RPMs and can be used directly for the build. See https://github.com/xcp-ng-rpms/ where various packages have changes already (some only to make them build properly in a clean environment).

See also this recent forum discussion: https://xcp-ng.org/forum/topic/183/git-repository-structure-and-conventions-for-rpms

Of course, we can still fork some repositories from https://github.com/xenserver... With caution because this means more maintenance work.

Considering closed, but don't hesitate to answer.
