### ISSUE TITLE
xcp-ng 7.6 install on IBM server x3650m3 fails with "efibootmgr: Could not set variable Boot000E"

### ISSUE THREAD

**Issue by sapcode** [xcp-ng/xcp#199]
Hi team,
we tried xcp-ng 7.6 install on IBM server x3650m3 but it fails with "efibootmgr: Could not set variable Boot000E", Screenshot attached.
Any ideas ?
![x3650m3_XCP_7 6](https://user-images.githubusercontent.com/10140758/59101273-be8b2d00-8928-11e9-822c-c5ca5861219f.jpg)

**Comment by sapcode** [comment]
Found aanother guy has same issue, trying to reset bios seetings to default:
https://discussions.citrix.com/topic/390297-failed-to-run-efibootmgr-xenserver-72-installation/

**Comment by olivierlambert** [comment]
Keep us posted.

Alternatively, try with XCP-ng 8.0 beta ISO.

**Comment by Daniel-Furcht** [comment]
Hi. try set first boot device to "Legacy Only" and reinstall from scratch.
I've seen some issues with UEFI boot on IBM X Servers

**Comment by sapcode** [comment]
Thank you Daniel, finally the following settings did the beast get booted:

![image](https://user-images.githubusercontent.com/10140758/59563324-af972f80-9038-11e9-9594-21f9f102c75a.png)

![image](https://user-images.githubusercontent.com/10140758/59563327-bd4cb500-9038-11e9-8ac9-354cd3daf2bb.png)

![image](https://user-images.githubusercontent.com/10140758/59563329-c50c5980-9038-11e9-8835-6bcb323497f4.png)

**Comment by MaXaMaR** [comment]
For me UEFI variables also don't work after VM being imported - boot stucks on Boot device: Hard Disk - success, grub-install tells that efi variables are not supported on this system. That happened on one vm (debian), another one imported OK in UEFI mode (centos).

**Comment by stormi** [comment]
> For me UEFI variables also don't work after VM being imported - boot stucks on Boot device: Hard Disk - success, grub-install tells that efi variables are not supported on this system. That happened on one vm (debian), another one imported OK in UEFI mode (centos).

Is that comment related to this bug report which is about installing XCP-ng? It looks like yours is about UEFI support for VMs...

**Comment by MaXaMaR** [comment]
yes that's for VMs

**Comment by stormi** [comment]
Then I suggest to open a thread on the forum first to help the community guide you in diagnosing the issue.

**Comment by futurefutsys** [comment]
the real reason is that the bootloader wants to write directly inside the machine address space as a jmp start to the bootloader it makes the linux main kernell spoofed due the kernell v3, which is an gcc mod uses the dev as a xen virtual image which want's off course survive a reboot  and that's where it's a problem due faking a dev inside the machine address making use off the 0xfe80:/64:0.0.0.0, or searches for an usb3 port due those have power on the usb root hub, once the bootloader lands inside that the machhine is hacked, and physicall, during reverse engeneering i lost a netgate xg7100-u, 2 pc's with nvidia as most important due i run 5 screens with 3 on 30 inch and high res , the osd off thhe screens were even hacked, the principle is easy, the problem lies in the time , as 20 became due unicode inside DNS the use off %20% void so lanch a browser in the shell with 0x20202020, you will be surprised, and the ack runs inside the c headers which are modified during runtime linking that's why the use off nginx is so massive inside linux distro's now, due apache is in DARPA due violation against the "The License" , with then use off php we run not https but run an url that now is allowed to use symbolycs, and that's where the posix communicates with the win api, simply by use off directory mapping in environments, as %SystemRoot% never forget that the hypevisor lives on mapping physicall address inside a segment that uses massive http calls like soap and xml , the kernell is lives on use off namespace and symlinks, as a dev uses null is no issue in linux but when that dev real device makes an systemcall with as objecct null in a C system you get a stack overflow , this runs on esxii,vmware workstation xcpng,xen,citric,hyperv,the IBM protects this by interfaces running inside a link so the base mac is the address and covers the full end ff:ff:ff:ff:ff:ff, which is writing Boot000E must be seen as hex B pointing to 0xE these are the cpu B register and E flag vor virt-d, the dbit inside the execute bit exploit,

**Comment by futurefutsys** [comment]
Never do that anymore, as the image loads outside git, the resource is in the 151 net,as you should know there are rules, the first octet is always four possible use r,g,d,c which is defined and declined by DARPA for R research,G government,D Defense,C Commercial, the master also should notice that I declare a file against the abuse off browsers and use off namespace on the machine it operates, as Moziilla Corporation under Company Copyright running the problem with all is most live in an OS, I move inside any so the files you store inside namespace <<%SystemRoot% /path pointing to the roaming folder off the user is all json,js,jsm,cgi,css,scl,json,txt,png, what normally should be deleted by the running process, only while the VS++ COM runs I change the enviromant parameter, so then the PID can't clean, that left massive inside machine on a physicall powered domain plant off IBM servers and all on machine ID with designated corporate protection by any attempt from any system attacking the phyisicall MAC space, the IP i don't give a dollar for, but when you store full address allocation by browser access the internall web service , and you make it a exploit by probing it as a dev (null)->* that's same as launching firefox 0xFFFFFF, fact the application makes the parameter as url inside the edit box is only the aplication that allows access inside such way, which means clear and plain as IE works the use off % is fingerprinting on local,with full access inside any file or code running, as in web a promise i give a fact, as the about:about pops behind runs chrome as parent handle off every browser, shame for netscape by not honnering the originall roadmap that even took a coders life as i remember , during that period the fine payd against Sun (c) Corporation by abuse off Java (c) was never posted , never forget your role in one file making a copyright disclamer gives me as company the possiblity to fine every part in that chain , for start the telco , the OS, the application, and my assets run in full allignment off Motorola Corporation, Cisco IOS, with Cisco as protector under all regulations in the ISO and IEEE particles , IBM (c) and it's relation, Zebra technologies (c), Symbol (c), Broadcomm (c), Nextell (c), C standard iso , and the BSD (c) , it's all funny for users but hit me and I collect such massive evidence ya never see what happens , the use off icmp by sending bitlanes in the msecs as formatter is Link-Locall <0x20> -->LAME and that screenshot, you forget that i see that that is a fakebios mapped over the real one, as the pci root never has a pipe and enumerate the childs on same ascii position with whitespaces inside the controller address , that's the SAS driver that compiles in runtime during the cold boot, the IMM sees the 0x01300 probing in the c,d,c,d,c,d, firmware changes the internall pxe ROM , and that's the real enumeration , next launch will be under my -->handle and as child will the browser end , as the W3C is gone the 2017 attacks started to deploy which was already coded in 2002, with 1996 as DOOMS day, my system runs in 1993, which makes the YYYY a problem due %20% is always TRUE in the flat file FALSE, as the domains run xxx--xxx-- which makes in a C calc a +, and << in unicode remakes // as www /\/\/\/\/\ , the problem with such work is that the url is a real path not a session which makes the xmlhttp wrapper void, and by a arping on the ip you get the ARP, which is in SOhO no issue, my ARP is a full logical local link address that maps the full ff:ff:ff:ff:ff:ff address space on that address which I can give a vlan on PORT stack, that's no cookie , but when i see the 4 adress then the DNS is really corrupted,as I never believe any real traffic would happen inside the DoD, but 1.1.1.1 is also just a ip6 inside capsulated off googles ip6 lane , so Cloudflare (c) be verry aware off data theft inside as I have no html5 controller but physicall sensorring by APC, and other partners, the aggression against tthose systems is not to take a zero day for , as a bitmap arises in mod and woff BOOTE, is just a BOOTP assign so you flash the ROM by a PXE ring loop , those are Red Hat C drivers you override ,  hope you see the issue inside as the irony is that i did win32 api snooping since first 95r1, probably my last post asswell in git due the zone is broken and i'm not a pkemon expo in the ring buffer 

Query: 151.101.192.133
Status: This WHOIS server does not have any records for that zone.
Handle: SKYCA-3
Name: Fastly
Organization: 
Street Address Line 1: PO Box 78266
City: San Francisco
State: CA
Postal Code: 94107
Country: United States

**Comment by nagilum99** [comment]
I guess that nonsense is part of a spambot?

**Comment by olivierlambert** [comment]
I reported it.
