### ISSUE TITLE
/boot/grub/grub.conf menu items not updated to 4.13 after in place upgrade

### ISSUE THREAD

**Issue by user-72632** [xcp-ng/xcp#355]
After doing an in place upgrade from 8.0 -> 8.1 RC using yum I noticed on boot that the boot menu items were still showing the xen 4.11 version and not 4.13. I know this is not a showstopper because it is merely a text change but should be remedied.

Also, I notice that NTP is obsoleted in favor of chrony. Has any mention of the update from ntp.conf to chrony.conf been mentioned anywhere?

One other little thing, after the initial install of 8.0 on a two disk software raid setup, I noticed that the swap partition was still named with the old label from the previous install. This caused the system to hang on boot for several minutes until the mount failed/timeout. Using swaplabel command to update the label to the new one from the old fixed the problem. This would only occur of course if you had a previous install on the raid devices. Just thought I would mention it even though this is for 8.0.

HTH

**Comment by stormi** [comment]
Hi. Thanks for the feedback. 

> After doing an in place upgrade from 8.0 -> 8.1 RC using yum I noticed on boot that the boot menu items were still showing the xen 4.11 version and not 4.13. I know this is not a showstopper because it is merely a text change but should be remedied.

I used to think like you and even [reported it to Citrix](https://bugs.xenserver.org/browse/XSO-907). It happens that it's *expected*, because those are fallback entries that are *not* updated via yum. Thus, if the new xen and kernel don't boot, you can boot the former.

> Also, I notice that NTP is obsoleted in favor of chrony. Has any mention of the update from ntp.conf to chrony.conf been mentioned anywhere?

The fact that chrony replaces ntp is documented in the RC announcement and will also be in the final release announcement. I've not seen any document from Citrix explaining to their users how to deal with that update. It should be transparent unless you have specific settings. Is your question related to such specific settings that you need to re-enable in chrony.conf?

> One other little thing, after the initial install of 8.0 on a two disk software raid setup, I noticed that the swap partition was still named with the old label from the previous install. This caused the system to hang on boot for several minutes until the mount failed/timeout. Using swaplabel command to update the label to the new one from the old fixed the problem. This would only occur of course if you had a previous install on the raid devices. Just thought I would mention it even though this is for 8.0.

Please open a separate issue for that. The behaviour in 8.1 has not changed so it may be still valid.

**Comment by user-72632** [comment]
-grub issue: Sorry for the noise
-ntp issue: thanks, missed that in the RC full writeup
-swap issue: will do
