### ISSUE TITLE
Raiding (3) ssds problems

### ISSUE THREAD

**Issue by MrWaste** [xcp-ng/xcp#373]
Hello, I really need to talk to you. I have a problem with XCP-NG software.
Computer Specs,

AMD Ryzen 7 2700X 3.7 GHz 8-Core Processor
ASRock B450M PRO4 Micro ATX AM4 Motherboard
Corsair Vengeance RGB Pro 16 GB (2 x 8 GB) DDR4-3200 Memory
MSI Radeon RX 580 8 GB ARMOR OC Video Card
Thermaltake Smart 500 W 80+ Certified ATX Power Supply

I have (3) Samsung 860 QVO 1TB Solid State Drives and wanting to raid them together to be 1 drive. The raid is in the bios that will be raid 0. After raiding the drives together do you know if there is a "raid driver" to read those drives after being raided together? Because on this motherboard you have to download the floppy disk driver to be able to load windows 10. I called the support team for Asrock and they said THEY HAVE NO IDEA IF IT WOULD EVEN WORK. So I decide to try XCP-NG support but can't find any because its only paid support :(

Sinerally,

Mr. Waste

![floppy disk](https://user-images.githubusercontent.com/49108816/79408195-99574a00-7f4f-11ea-9f5b-897a3d7aa70f.png)

**Comment by nagilum99** [comment]
Hello Mr. Waste.
This pretty much a waste of time. *pun intended*
A) You're doubleposting your problem on the 'bug'tracker.
B) There's probably noone caring about chipset-RAID, also called fakeRAID. If you want to RAID, use XCP-ng software RAID functions.
C) Since this is no bug, you could try to get more help on the forum (which is (your) community support: https://xcp-ng.org/forum/ - but let's stay realistic: There will be probably no help regarding chipset RAID as it's the worst kind of RAID.
    Use either a hardware RAID-Controller or the software-RAID function. See above: forum may assist you there.

Greetings

**Comment by stormi** [comment]
This is indeed a question for the forum. Closing.
