### ISSUE TITLE
Allow core scheduling

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#407]
For our next release, we should be able to enable core scheduling. It's just an option to pass on Xen via Grub (`sched-gran=core`).

Should we expose it via a XAPI plugin? Or extend XAPI? I don't think there's some "clean" way to change Xen boot parameters outside a Grub file modification.

**Comment by rjt** [comment]
I think it would be nice enough to have multiple grub entries, one with
pre-populated core scheduling for instance.   But since we would probably
want and possibly need all hosts to have the same scheduling algorithm,
then XAPI makes sense.  A global XO/xsconsole place to set which grub entry
to reboot into for all hosts.  If users want to test something, they could
still reboot manually.

**Comment by benjamreis** [comment]
`sched-gran` entry doesn't survive an upgrade.
We need to document it if we don't fix it.

**Comment by stormi** [comment]
Also, current implementation doesn't update the grub entry for kernel-alt if there's one. Since kernel-alt is a testing/troubleshooting kernel, this is not a big issue, but it will need to be documented too.

**Comment by stormi** [comment]
Here's where the `dom0_mem` parameter is handled during upgrade: 
* https://github.com/xcp-ng/host-installer/blob/0fb016b991455c9bc07be7bec808087397167a88/product.py#L383
* https://github.com/xcp-ng/host-installer/blob/0fb016b991455c9bc07be7bec808087397167a88/backend.py#L323
