### ISSUE TITLE
pciback missing after upgrade

### ISSUE THREAD

**Issue by hkparker** [xcp-ng/xcp#412]
I think I'm experiencing the same issues as #320, or at least something similar.  I recently upgraded from 7.6.0 to 8.1.0, and after the upgrade my VM that uses PCI passthrough wouldn't successfully boot.  I followed the steps [here](https://xcpng.org/docs/compute.html#pci-passthrough), after noticing that one of the PCIe addresses changed (weird, but ok, I swapped out one of the cards), and when I got to `xl pci-assignable-list` the output was `libxl: error: libxl_pci.c:427:libxl_device_pci_assignable_list: Looks like pciback driver not loaded`.  modprobe says pciback was not found.  I would very much like to avoid having to re-install 8.1 from scratch as it would be very time consuming to restore my previous setup.  I'm curious if there's any information out there on what's going on here and how I can fix it in my current install.  Thank you.

**Comment by hkparker** [comment]
Did some more digging after looking at other threads debugging pciback and here's what I found.

My kernel boot parameters had an incorrect PCI address, and dmsg revealed the following: `xen_pciback: Error parsing pci_devs_to_hide at "(0000:82.0.0)"`.  Was supposed to be `0000:82:00.0`.  So clearly the module is present.  I fixed that and rebooted, and now everything appears to be working.  `xl pci-assignable-list` shows me what it should, devices are passed to the VM.  I think this was a case of the module simply not being present if its parameters are incorrect at boot.  Hope this helps someone else, remember to check your work.

**Comment by rjt** [comment]
I have used etc udev rules.d to create symbolic links to /dev/sdX based on the drive serial number.   This makes the names of the drives consistent even if another drive is inserted in the middle or one is removed.   
So if sdf points to fast NVMe drives, instead of referring to /dev/sdf, the iSCSi deamon only looks for /dev/NVMeRaidVirtualMachinesFast

Although, preboot time such as grub parameters, udev has not been started, so udev will not work in this case.  Hopefully, there is some way such as a kexec call or even a kexec reboot after it figures out the PCI address.
