### ISSUE TITLE
XCP-ng Center 20.04.00 will not connect to XCP-ng 8.2

### ISSUE THREAD

**Issue by baclaeys** [xcp-ng/xcp#451]
After upgrading one of my XCP-ng 8.1 servers to 8.2 I received the following error message:

"Connection Refused
This version of XCP-ng Center is out of date and cannot connect to xcp-ng04.

You can get a compatible version of XCP-ng Center from the following location:"

As far as I know, this is the latest version of XCP-ng Center.  I also use Xen Orchestra, so I am still able to connect to the server.  The server was upgraded with ISO burned to a flash drive as opposed to a yum style upgrade.  Please let me know if any additional information would be helpful.

**Comment by stormi** [comment]
XCP-ng Center is maintained by the community, specifically by one member and he hasn't had time to build a new release for XCP-ng 8.2. The official client, Xen Orchestra, is ready for XCP-ng 8.2.

This report is a duplicate for https://github.com/xcp-ng/xenadmin/issues/195 but since there will be likely others reporting the same on this repo, I will leave it open as documentation for now.

**Comment by baclaeys** [comment]
I must have missed that post.  I would be happy to delete it and add it to the existing post.

Brian

**Comment by zsocialmedia** [comment]
I have same issue. Can you help? Thanks
