### ISSUE TITLE
XCP-NG Center where is that!?

### ISSUE THREAD

**Issue by prilly-dev** [xcp-ng/xcp#455]
XCP_NG 8,2 is not currently compatible with the xcp-ng center.
What in gods name are you guys thinking!? releasing xcp-ng 8.2 before center is ready!? are you guys joking?

And you DONT mention this in the release note? not everybody is interested in using the crapware xcp-ng is pushing to admin,

**Comment by nagilum99** [comment]
As I absolutely understand you, xcp-ng center is not part of this repo. It's community developed and thus... sadly not really coordinated.

I'm not happy either, and I expect a bunch not to be. The whole situation is so-so.
Only way currently: Use (free) XOA appliance (or build yourself).

**Comment by prilly-dev** [comment]
> 
> 
> As I absolutely understand you, xcp-ng center is not part of this repo. It's community developed and thus... sadly not really coordinated.
> 
> I'm not happy either, and I expect a bunch not to be. The whole situation is so-so.
> Only way currently: Use (free) XOA appliance (or build yourself).

This is just crazy, here XCP-NG advertise themself as drop in replacement for xenserver but they fail to mention to you that they will gradualy fore you to switch to that crapy XOA, making it very difficult when you are locked in, no i am not going to use XOA even if i got payed.

I will give it a couple of days, if xcp-ng center is not available i will transit back to xenserver for good.

Community backed, kiss my ass, xcp made the first xcp-ng center to lure xenserver users in, then they hope they will change to xoa and prefferable lock them in and sell them subscriptions. that is the tought behind it. They realy showed themself when failing to mention this in release notes! 

This is just it!

**Comment by olivierlambert** [comment]
*sigh* and *taking a deep breath*

How on earth can you expect to deserve anything if you don't respect people in the first place? Your tone is utterly incorrect.

Here is some facts:
1. Since XCP-ng project inception, we always said that XCP-ng Center was only a community maintained project (it's even in our [official documentation](https://xcp-ng.org/docs/management.html)). We (people at Vates, doing all the work behind XCP-ng itself) NEVER touched any part of XenCenter code. One person, @borzel decided to put some effort (for free) to create a fork of XenCenter and name it XCP-ng Center. We are hosting the repo on this Github org, because XCP-ng is an Open Source project, welcoming efforts of people to bring whatever they want it.
2. It's not like there's no alternatives. Open Source alternatives, meaning you are not forced to purchase anything. As in our doc, it's explained you can use `xe` or XO. For people who won't want to deploy, we are also preparing XO Lite (cf the doc again)
3. Instead of going here and calling our work "crapware" (I suppose you were talking about Xen Orchestra, which is in fact made XCP-ng Project possible, otherwise you would be still using Citrix product or something else), you can help XCP-ng Center project and contribute to the current work in progress to make it work on 8.2: https://github.com/xcp-ng/xenadmin/issues/195
4. Even better: provide constructive feedback on why XO isn't filling what you need. It's fully Open Source and you can even contribute to it.

So the all conspiracy theory you have is completely non-sense, because all alternative are Open Source and available for free.

**Comment by nagilum99** [comment]
As said: I understand the anger.

But in the end: This is still OSS and you could contribute to that. Also noone is forcing you to use XCP-ng.
Noone gets a pence for you using, complaining/ranting, not contributing. You might understand what I'm saying.

Also: For production systems it's ever been a good advice to not be in front line for upgrades. For nothing. Never, ever.

**Comment by prilly-dev** [comment]
And here you are marketing XO in the middel of this crisis, i dont want to hear anyting about xo, and for shure will never use it. and if xo is what keeps xcp-ng running i think its the best to leave for xenserver again. i happily paying for the license there to keep the possibility to use xencenter.

**Comment by olivierlambert** [comment]
What on earth are you talking about? XO is free, you can have ALL the features for free. What's wrong with you?

**Comment by nagilum99** [comment]
@olivierlambert: Send him an offer for feature implementation to fix xcp-ng center - he says he's willing to pay. ;)

**Comment by olivierlambert** [comment]
We should ask if @borzel will accept donations to help the project :+1:

**Comment by prilly-dev** [comment]
> 
> 
> What on earth are you talking about? XO is free, you can have ALL the features for free. What's wrong with you?

As i said initialy, i would NOT use XOA even if i got payed to use it. what worng with me, i got caught in xcp-ng tvist of forcing their users to use xoa. dont tell me the xcp-ng team didnt know that xcp-ng center was incompatible with xcp-ng 8.2, and you still did not mention this in the release note, what else in the future are this team going to "miss" telling about that is crucial to know but dont fit their financial plan?

**Comment by prilly-dev** [comment]
> 
> 
> We should ask if @borzel will accept donations to help the project 👍

yes! ofcourse!  i will be happy to contribute

**Comment by olivierlambert** [comment]
But Xen Orchestra is free, you can install it entirely freely from the sources. If you don't like it, providing your feedback will help to improve it the way you'd like.

If you crave that much about XCP-ng Center, go help the project.

Again, I think you have a deep misconception of what is Open Source. If you want something, go for it. If you don't like something, provide feedback. If there's enough similar feedback, other people will implement a solution to your problem. If there isn't, you can always code it yourself. And if you can't, you can pay for it.

If you don't contribute, nor pay, nor anything and requiring something for you while insulting people (and without explaining why) you won't have anything. Does this sound logical?

Also, we knew that XCP-ng Center wasn't ready yet despite some progress on their project side, but I repeat: we NEVER said we supported XCP-ng Center, at any moment. We did NOT created XCP-ng Center at the first place. So we never miss stuff that we support, which is explaining clearly in our doc. If you are not happy with that, use your anger to make something productive instead of insulting us.
