### ISSUE TITLE
CentOS Project shifts focus to CentOS Stream

### ISSUE THREAD

**Issue by DSJ2** [xcp-ng/xcp#466]
Does Red Hat's decision to eliminate CentOS and to build RHEL from CentOS Stream impact XCP-ng?

See https://blog.centos.org/2020/12/future-is-centos-stream/

**Comment by rjt** [comment]
Stream will still have five years.
 End users will be able to contribute back to RHEL so it wont be just a
free consumer clone of RHEL.   Since RHEL is now two way, quite possibly
XCP-ng will end up contributing back upstream to  RedHat RHEL.

Recommend the following podcast discussion.

LinuxUnplugged 383 “Murder of a Distro”
https://linuxunplugged.com/383 mentioned that the RHEL source RPMs will
still be available for things like “Oracle UnThinkable Linux”.

**Comment by nagilum99** [comment]
Well... first of all: XCP-ng is based on Citrix HV. So it first affects them. Also one has to keep an eye on if "Rocky" will be a proper replacement with proper release cycle.
Many people are pretty unhappy about that rolling release stuff as it's not good for stability, debugging and LTS.

https://github.com/rocky-linux

**Comment by olivierlambert** [comment]
Please see https://xcp-ng.org/forum/post/34224 and follow the discussion there if needed :+1:
