### ISSUE TITLE
VMs sporadically state=running on failed host

### ISSUE THREAD

**Issue by adaemmer** [xcp-ng/xcp#500]
We are currently running a continuous test on a two server setup. 

- installed xcp-ng version is 8.1.0
- both servers are in a pool
- HA is **not** enabled
- VMs are stored on a ISCSI target
- VMs are started on pool master 
- pool master is switched off (hard power failure)
- slave becomes master via `xe pool-emergency-transition-to-master`
- former slaves starts VMs
- do some testing on started VMs
- start former master server (power up)
- wait until former master server is booted and has become slave
- repeat

In run number **94** our test stops because VMs didn't become reachable after the new master should have had started them.
So we run `xe vm-start uuid=XXXXXXXXXXXXXXXXXXXXX` ourselves.

```
You attempted an operation on a VM that was not in an appropriate power state at the time; for example, you attempted to start a VM that was already running. The parameters returned are the VM's handle, and the expected and actual VM state at the time of the call.
vm: XXXXXXXXXXXXXXXXXXXXX (vm-name)
expected: halted
actual: running
```

Unfortunately xcp-ng thinks the VMs are still running for all VMs. We guess this issue could be solved either by `vm-reset-powerstate` or booting the former master server, but we don't want to break this status until further analysis.

VMs parameters shows that `resident-on` is still the former master server.

Any ideas what could cause this behaviour?

**Comment by olivierlambert** [comment]
I'm not sure to get everything but here is a bit of context.

It would have been extremely risky for XAPI to consider a host dead except if you tell it is. What if the VMs are still running and the link to the iSCSI is still working? (but you just lost the management link).

If XAPI consider those VM dead and they are not, booting them will corrupt the data.

**Comment by adaemmer** [comment]
@olivierlambert your absolutely right. I looked a little bit deeper in our test and we actively reset the power state when we are sure that the server is gone....which seemed to have failed.

So error is on our site. Sorry for bothering you and btw. many thanks for your work.

**Comment by olivierlambert** [comment]
So where does it fail exactly in your test? I'm not sure if ` xe pool-emergency-transition-to-master` will consider the host dead, if it's not enough, I vaguely remember a way to tell that a host is dead with all its VM (but it's manual, because XAPI can't guess that).

Note that in HA, there's a heartbeat on the storage for exactly that reason: a host is alive as long it's reachable from mgmt network AND writing the heartbeat on the shared SR.
If that heartbeat is too old (older than XX secondes) and the host doesn't answer from the mgmt, it's rather safe to decide automatically to kill it (the host will enter in autofencing/reboot). Then VMs will be started on the other pool members :)

So not using HA is very fine, it's just you need to tell XAPI that the host is really dead, because otherwise there's no way to guess it from its own perspective.

**Comment by adaemmer** [comment]
I have to do detailed analysis tomorrow, but at first look we do `xe pool-emergency-transition-to-master` and afterwards `xe vm-reset-powerstate` with uuid and force for all VMs we expect on former master. And this seems to be broken on our site, no in xcp-ng.
