### ISSUE TITLE
Windows PV Drivers for XCP-ng now 2 years old and 8.2 LTS reflections.

### ISSUE THREAD

**Issue by user-36428** [xcp-ng/xcp#505]
Just an observation but the latest Windows PV drivers have not been updated for two years. I thought I would take this opportunity to mention this as it appears they will need to be recompiled and/or resigned due to the UEFI Secure Boot issue. If the XCP-ng devs are going through the effort of doing this, it makes sense to use the most up to date Windows upstream PV drivers to test with and re-sign. I understand there was one developer @borzel giving his precious time for this effort some time ago but at some point the XCP-ng team should take this opportunity to support this driver effort and not to relegate it to contribution only effort.

A second observation is to address the scope of the 8.2 LTS work. In keeping with the Citrix philosophy on this hypervisor, it was initially decided to not install new features to a LTS release only security updates and fixes. By tainting the LTS release with new features, you risk destabilizing the long term viability of this release. All new major features were relegated to interim next releases such as 8.3 or 8.2.1 if you will. The 8.2 LTS line would always remain untainted by new features. I consider some of the newer updates to the 8.2 release as major updates or feature sets.

Thanks for listening....

**Comment by olivierlambert** [comment]
1. We are actually working on this, especially for guest secure boot support.
2. What are you talking about, exactly? I don't think we added any new major feature in 8.2. We obviously plan to keep 8.2 as stable as possible. We will never release any potentially risky feature in it.

**Comment by user-36428** [comment]
@olivierlambert thanks for listening!
1. Great to hear. Relying on buggy updates from Citrix is too much. A solid release (non-RC) is very much appreciated.
2. MooseFS in an LTS as an example. I'm not hassling anyone, just voicing support for a clean no new feature set release. Given the Intel security debacle coupled with their respective Xen updates, it is enough these days to keep a sever stable. Add to that, the extensive use of PCI passthrough with SCSI and Nvidia cards, and a Windows environment, and you get the trifecta of instability over this latest year and a half. 
3. Full disclosure: no support contract as yet. Hoping I won't need one!

**Comment by olivierlambert** [comment]
Okay so let me explain some things:

2. You should have read our update blog more carefully: MooseFS driver **IS NOT INCLUDED** by default. You have to install it. So it doesn't change anything in terms of stability.
3. It doesn't work like this. If your XCP-ng is running in production, we won't be able to assist if you don't have a support subscription before. See details below.


**It's like a car insurance: you can't get one for your car after you crashed it.**

Also, if you wonder, we do not offer one shot support, because our model is to get a stable revenue stream to be able to pay XCP-ng developers (not only to fix issues, but to improve it continuously). As you can imagine, the kind of profiles we need to hire and keep are hard to find and not cheap. That's why one shot support won't be sustainable for us (it is for some companies selling licenses AND support: we only sell support). I hope you understand.

**But if nobody took support or "only when they need"**, XCP-ng simply couldn't exist. It would also mean our interest would have to get a poor QA, because problems would drive more customers. It's not really aligned with your business needs, that's why we prefer to trust people to get pro support before they got an issue.

So this attitude on "waiting to have a problem to get support" is not helpful for the project at all.

**Comment by stormi** [comment]
About MooseFS, technically the driver *is* installed on the system along with other drivers that we provide, but it's not enabled, which means that the driver file is never loaded into memory by `sm` in the default configuration. So from your running XCP-ng's point of view, it's like they're not present. Only users who want to give it a try will follow the documentation and enable it.

**Comment by stormi** [comment]
I have updated the blog post to indicate that there's no risk of regression related to the addition of this MooseFS SR driver.
