### ISSUE TITLE
XCP-ng netinstall ISO

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#53]
We could easily host a HTTP service with the XCP-ng ISO content and distribute then a small ISO doing a netinstall, pointing by default toward our HTTP

**Comment by olivierlambert** [comment]
* Test URL is available on https://xcp-ng.org/install (maybe we should add "stable" to point toward the current stable?)? But I like this short URL (easy to remember)
* The ISO will be basically stripped down to the minimum, what we'll be the new ISO size?
* Maybe we should modify the install to automatically point to our repo?

**Comment by stormi** [comment]
It would seem more logical to have it on updates.xcp-ng.org so that replicating mirrors can replicate it at the same time as the repositories. And have one directory per release of XCP-ng. Not that being able to net-install old versions would be highly important (though can help in testing for regressions), but being able to test dev versions is a must-have so we need at least two versions. And if we have two, let's have them all. 

If we really need short URLs, we can always have https://xcp-ng.org/install redirect towards https://updates.xcp-ng.org/install/latest (but that one is not that long already).

**Comment by stormi** [comment]
Ideally, but that would require installer changes, the installer itself should be downloaded from the repo and should use the existing RPM repositories for installation rather than making us duplicate RPMs. This is how net-install of linux distributions works.
- makes testing easier, just push a new RPM and the dev net-install will use it
- automatically installs the latest updates

But that's not for now :)

**Comment by olivierlambert** [comment]
Okay how do you want to spread the tasks for an initial "announcement" in the next weeks?

I can create the Nginx virtual host URL and redir if you like

**Comment by stormi** [comment]
* Either one of us can create https://updates.xcp-ng.org/install/{7.5,latest symlink, dev (symlink to 7.5 for now)}
* I let you handle the nginx and redir stuff
* I will check with @nraynaud how the netinstall ISO is built (build scripts pushed to repositories? etc) and we can probably add a patch to automatically pre-fill the URL field with https://updates.xcp-ng.org/install/latest

Anything else?

**Comment by olivierlambert** [comment]
Also we should remove the "choice" of "local" from the install media (you have "local", which is the CD, HTTPS and NFS). If it's a netinstall, there is 0 chance to have the RPMs on the ISO so we could remove it.

**Comment by nraynaud** [comment]
@stormi for the prototype I just deleted the rpms from my working directory before running generate.sh

one step further, the install.img can be downloaded on HTTP (not HTTPS, tho)

**Comment by stormi** [comment]
The net-install installation ISO has been released. Closing.

**Comment by marcelmah** [comment]
Hi,

I've been using the netinstall version the last couple of days to reinstall some servers from Xen 7.2 LVM to XCP-ng 7.5 EXT and I noticed that when I boot using UEFI the installer does not function.

I get the option for local media (not working offcourse) and the HTTP option has no content (no URL prefilled), when I boot the same media on the same server but now in legacy BIOS mode everything works fine.

**Comment by nraynaud** [comment]
Hi @marcelmah 

I just tired in VirtualBox with EFI, using the netinstall image available there: https://xcp-ng.org/#easy-to-install and I got the installation to complete, including the choice of remote installation. There might be a difference between various UEFI systems.

Can you describe your underlying hardware in more details please?

Nicolas.

**Comment by marcelmah** [comment]
It's a Intel server (complete: chassis, mainboard, and of course the CPU's). Don't know the exact model, can check tomorrow if required.
