### ISSUE TITLE
xcp-ng installation error - Ryzen 7 5700x

### ISSUE THREAD

**Issue by cairoapcampos** [xcp-ng/xcp#566]
I set up a computer for virtualization studies. However, when initializing the USB stick with xcp-ng, the message `CPU Panic 0: Xen Bug in iommu_init.c:1419` is displayed.

Configuration:

**Motherboard:** MSI Mortar Max B450m
**Processor:** Ryzen 7 5700x
**XCP-NG:** 8.2.1

I changed secure boot from UEFI to legacy and the error persisted.

Is my hardware incompatible ?

**Comment by olivierlambert** [comment]
Hi,

For that kind of hardware question/compatibility, the forum is better, since you might directly discuss with people in the community with similar hardware: https://xcp-ng.org/forum

In the meantime, try to enable x2apic feature in the BIOS, that's likely the issue (see this thread: https://xcp-ng.org/forum/topic/5652/panic-on-cpu-0-xen-bug-at-iommu-init-c-1419)
