### ISSUE TITLE
Creating a VM from a template on command line takes longer than it should

### ISSUE THREAD

**Issue by marcusbooyah** [xcp-ng/xcp#61]
It seems that creating a VM from an existing template on the command line takes a few minutes. Creating an identical VM from the XCP-ng Center takes only a few seconds. I have reproduced this on different hosts and different hardware.

[root@WRT-00-XEN-03 ~]# date
Tue Sep 11 23:29:43 PDT 2018
[root@WRT-00-XEN-03 ~]# xe vm-install template=<template> new-name-label=TEST sr-uuid=<UUID>
[root@WRT-00-XEN-03 ~]# date
Tue Sep 11 23:33:21 PDT 2018

**Comment by olivierlambert** [comment]
I assume `xe` makes you a full copy instead of using the underlying snapshot mechanism. Please use tab key to see if you have extra fields to use related to fast clone or full copy.

**Comment by marcusbooyah** [comment]
I didn't see and options for a fast clone. Before we upgraded to XCP (on xenserver), this used to be fast. It's fairly recent that this command takes a long time.

**Comment by jefflill** [comment]
It looks like this option is why the UX is fast:

![image](https://user-images.githubusercontent.com/4908431/45443289-0d958180-b679-11e8-8195-a902c87c83c7.png)

`xe help vm-install` doesn't show an option for enabling fast clone on the command line.  Is there an option for this or do I need to call the REST API>

**Comment by jefflill** [comment]
Yeah, I’m talking about my code.  I’m working on some tools to help automate Docker cluster deployment (and more) to XCP, Azure, AWS...

My code currently SSHs into the XCP host machines and runs **xe** commands there to provision the VMs I noticed the speed difference after I added a feature that allows folks to specify the storage repo for the Docker VM disks.

Based on you advice, I should probably recommend (and default) to doing a full clone since these VMs will tend to be around for a long time.

BTW: We’re super excited about the XCP-ng effort!  It was great fun installing it and not seeing those yellow licensing warning icons in XenCenter any longer.
