### ISSUE TITLE
Please fix HTTPS settings on xcp-ng.org domain

### ISSUE THREAD

**Issue by PeS-hkfree** [xcp-ng/xcp#65]
Hello,
can you please fix https settings at server xcp-ng.org, so it's useble in newer browsers?
FF 60.2.0 ESR reports this error:

Your connection is not secure

The website tried to negotiate an inadequate level of security.

xcp-ng.org uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe. The website administrator will need to fix the server first before you can visit the site.

Error code: NS_ERROR_NET_INADEQUATE_SECURITY

Best regards,
Petr Sindelar

P.S.: Keep up good work, already reinstalled XS 7.6 to XCP-ng 7.5 and will stay with you :-)

**Comment by olivierlambert** [comment]
I can't reproduce with FF 62.0. Anyone else got the issue?

**Comment by borzel** [comment]
Firefox 61.0.1 (64-Bit) on Ubuntu 18.04

![grafik](https://user-images.githubusercontent.com/5782951/45848869-54960d80-bd30-11e8-8218-adaa1a983c7d.png)

**Comment by PeS-hkfree** [comment]
Hms, so maybe it's problem with older CentOS (6.10) with firefox 60.2.0esr (64-bit). My mistake I wrote 62 when it 60.2....

**Comment by PeS-hkfree** [comment]
@borzel No, there isn't such stuff (not corparet network and even at our company where I was yesterday is something like that, I do setup on firewalls and routers).

**Comment by olivierlambert** [comment]
Do you have a more detailed log on the issue? Also, can you try a more recent version of FF?

**Comment by stormi** [comment]
I would suspect an outdated list of CA on the system, but I'm just guessing.

**Comment by stormi** [comment]
Or rather this: https://bugzilla.mozilla.org/show_bug.cgi?id=1323209

**Comment by PeS-hkfree** [comment]
Error from google-chrome Version 49.0.2623.112 (64-bit):

This site can’t be reached

The webpage at https://xcp-ng.org/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

**Comment by PeS-hkfree** [comment]
damn, 60.1.0esr on centos7 on 2nd ntb is working...going to update to 60.2.0esr

**Comment by PeS-hkfree** [comment]
But it looks like for some client's it can cause problems, look at this report: https://www.ssllabs.com/ssltest/analyze.html?d=xcp-ng.org

**Comment by stormi** [comment]
Statically linked Firefox from mozilla.org would probably work. I'm almost sure there's an issue with a system lib in that Centos 6.

**Comment by PeS-hkfree** [comment]
Probably, because same version on CentOS 7 is working, about:config TLS settings is same on both (all default)...

**Comment by stormi** [comment]
Interesting report from ssllabs indeed:

```
Chrome 49 / XP SP3: Server negotiated HTTP/2 with blacklisted suite
Firefox 47 / Win 7: Server negotiated HTTP/2 with blacklisted suite
IE 8 / XP: Server sent fatal alert: handshake_failure
```

**Comment by stormi** [comment]
It seems similar to https://www.jeffgeerling.com/blog/2016/fixing-errspdyinadequatetransportsecurity-ssl-error-chrome

**Comment by thctlo** [comment]
You get an F here.  https://securityheaders.com/?q=xcp-ng.org&followRedirects=on 

Since its a wordpress website.  use this plugin for the header security. 
https://wordpress.org/plugins/http-security/ 
Review it and enable it. You wil go from an F to B or A. 

```
Chrome 49 / XP SP3: Server negotiated HTTP/2 with blacklisted suite
Firefox 47 / Win 7: Server negotiated HTTP/2 with blacklisted suite
IE 8 / XP: Server sent fatal alert: handshake_failure
```
This is not important at all, or the OS is EOL or the browers is EOL or the use cypher is EOL. 
So why enable it at all.

**Comment by stormi** [comment]
We now get an A in https://securityheaders.com/?q=xcp-ng.org&followRedirects=on

**Comment by thctlo** [comment]
👍

**Comment by thctlo** [comment]
anyhow. 
You can remove : 
IE 8 / XP 		   No FS 1		   No SNI 2 | RSA 2048 (SHA256) | TLS 1.0 | TLS_RSA_WITH_3DES_EDE_CBC_SHA
and 
Java 6u45 				   No SNI 2 | RSA 2048 (SHA256) | TLS 1.0 | TLS_RSA_WITH_AES_128_CBC_SHA                                                                 					 	

since they dont support SNI, these wil never work. 
and these: 

TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA

are all marked as weak, i suggest, remove them, test again and now see the differences. 
you only miss 3 or 4 or the, but these are all old unmaintained os's or browsers.
