### ISSUE TITLE
[Windows Client Tools] - Management Agent switches from installed to not installed

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xcp#79]
Client Tools Version: 8.2.2-RC1

seems to be the same as Update2 here: https://github.com/xcp-ng/xcp/issues/23#issuecomment-411240255

**Comment by borzel** [comment]
The `Management Agent Updater` was removed, this caused a hickup in the ManagementAgent-Service and restarted it.

Solution: `Management Agent Updater` back

**Comment by borzel** [comment]
Solved with: https://github.com/xcp-ng/win-xenguestagent/releases/tag/v7.0.2

**Comment by borzel** [comment]
Also solved with: https://github.com/xcp-ng/win-pv-drivers/releases/tag/v8.2.2-RC2

**Comment by thiesengmbh** [comment]
Hello, i installed RC2 on Windows Server 2016 Standart and the Management Agent still switches from installed to not installed

**Comment by borzel** [comment]
@thiesengmbh did you clean your VM from any client tools and PV-Drivers bevore?

**Comment by borzel** [comment]
@thiesengmbh Issue confirmed!

**Comment by borzel** [comment]
@thiesengmbh installing the .Net 3.5 feature seems to resolve this issue for Windows 2016
Please try and report back!

**Comment by borzel** [comment]
naah... my test Windows 2016 VM was stable ... but after cleaning all the drivers and testing again from a cleanest state -> Management Agent is still unstable 😭

**Comment by siodor** [comment]
@borzel 
As requested on IRC I've done some testing with several Windows versions and I'm sorry to report that I've managed to reproduce this problem on Windows 10 Pro N (64-bit) German and Windows Server 2008 R2 (64-bit) English.

On both fresh Windows installations I didn't managed to get the "XCP-ng-Client-Tools-for-Windows-8.2.2-RC2" installer working. Repeated rebooting, repair installation, etc. all didn't helped.

What helped was to first install "XCP-ng.PV-Tools.-.drivers.only.-.8.2.1.beta" and then after rebooting the "XCP-ng-Client-Tools-for-Windows-8.2.2-RC2" package installed without a problem. Reversing the order also worked somehow strangely and I've noticed that once I've installed the "xeniface" package that the flickering of the console window in XCP-ng Center started. Also just removing xeniface by itself fixed the flickering again after a reboot. Of course the Management Agent didn't worked but maybe this interaction dependency gives you a clue.

Btw. my first try to reproduce this was on Windows 7 but I gave up after several hours of trying because during my Windows Update session to get this Windows 7 Pro N (64-bit) English up to the latest updates I've either somehow installed the Citrix drivers (though I don't remember clicking them) which are provided through Windows Update or they came automatically through the driver update mechanism.  Anyway, it turned out to be absolutely impossible to get rid of them. I've documented this extensively, you can contact me if you want all this stuff.

**Comment by siodor** [comment]
@borzel 
Did some further testing on Windows 7 Professional N (64-bit) English and can confirm that the problem also exists there.

To get to this I first had to overcome the problem with the pesky Citrix drivers always coming back from the dead.
[Left over Citrix files.txt](https://github.com/xcp-ng/xcp/files/2545733/Left.over.Citrix.files.txt)

I'll attach my notes to this comment, I hope it makes a bit of sense.

**Comment by siodor** [comment]
@borzel 
The problem Management Agent switching between installed/not installed also exists on Windows 8.1 Professional N (64-bit) German and Windows Server 2012 R2 (64-bit) English.

What I also found out is that disabling automatic driver searching in Windows Update prevents the Citrix drivers from being automatically installed on a fresh Windows installation or after removing the Citrix driver packages with pnputil. I got the idea from here:
https://superuser.com/questions/920322/blacklist-certain-devices-so-windows-doesnt-download-new-drivers-change-wind?rq=1

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching]
"SearchOrderConfig"=dword:00000000

where:

0 = "No, let me choose what to do - Never install driver software from Windows Update"
1 = "Yes, do this automatically (recommended)"
2 = "No, let me choose what to do - Install driver software from Windows Update if it is not found on my computer"

**Comment by borzel** [comment]
Hello together, here some news: Just found out, that the (WMI-)Errors I currently hunt and try to resolve are also present on the drivers from Citrix....

💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥

AAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

💥 💥💥💥💥💥

**Comment by borzel** [comment]
It's time to test again: https://github.com/xcp-ng/win-pv-drivers/releases/tag/v8.2.1-beta1

**Comment by borzel** [comment]
Note to myself:
* general WMI errors, also present with Citrix PV-Drivers, reason unknown
* xenguestlib: error on pointer to int32 conversion (https://github.com/xcp-ng/win-xenguestagent/blob/f4353ff3064d47493821f1c95a5ed46efdf59bf4/src/xenguestlib/Win32Impl.cs#L751)
    * Management Agent and xenguestlib is compiled as 32 bit to avoid this (prooved with debugger)

**Comment by borzel** [comment]
should be resolved with https://github.com/xcp-ng/win-pv-drivers/releases/tag/v8.2.1-beta1

see also: https://github.com/xcp-ng/xcp/issues/23#issuecomment-439737249
