### ISSUE TITLE
Unable to migrate VMs in a pool during upgrade (using local storage)

### ISSUE THREAD

**Issue by markhewitt1978** [xcp-ng/xcp#90]
Tested on upgrade to 7.4 -> 7.5 and update 7.5 -> 7.6 with the same result.

I'm upgrading a pool by means of migrating all VMs from the master to other pool members, then yum updating the master following instructions and reboot. This works successfully.

However upon then attempting to move VMs back onto the master that are running on other machines I get "This operation is not supported during an upgrade"

This is the same on XCP-ng Center and Xen-Orchestra.

**Comment by stormi** [comment]
Thanks for reporting this issue. Is there anything useful in the logs? https://github.com/xcp-ng/xcp/wiki/Logfiles

**Comment by markhewitt1978** [comment]
No theres' nothing in the logs that appear related to the issue.

**Comment by stormi** [comment]
Hi. I did the test and could reproduce the issue. I suppose the host *knows* that it's been upgraded but does not know that the upgrade ended.

**Comment by stormi** [comment]
According to the source code, live migrate is disabled during pool upgrade for VMs that are on local storage repositories. It is OK for VMs on shared storage repositories.

Would this explain why it wouldn't work in your case? And explain why it worked on another pool?

I've made the test both with `yum update`-style upgrade, and with ISO upgrade and got the "This operation is not supported during an upgrade" message in both cases, so I don't think it's related to the upgrade method.

**Comment by markhewitt1978** [comment]
Yes I do have VMs using local storage, as I don't have enough shared for everything.

Why should this be a problem, as I can live migrate say 7.5->7.6 when they are standalone servers so why not when there's a pool upgrade? It won't even let me migrate out of the pool.

**Comment by stormi** [comment]
That's how it has been coded by XAPI's developers, but I don't know exactly why. It does feel a bit restrictive.

**Comment by stormi** [comment]
Similar issue in Citrix forums, with no proper solution except upgrading the other hosts :/
https://discussions.citrix.com/topic/386132-cant-migrate-from-70-to-71-in-a-pool

**Comment by stormi** [comment]
I have built experimental XAPI packages that remove the restriction on "storage motion" during a pool upgrade. It may work, or it may crash your VMs during the migration. Actually it is known to crash HVM linux VMs, but that's not related to my changes. That's a separate bug that we reported to the XenServer project (see #111).

I'd be interested in the result of the migration of a windows VM because I have none at hand right now.

To test, on the 7.6 upgraded master:
```
wget https://updates.xcp-ng.org/tmp/xapi/{xapi-core-1.110.1-1.2.xcp.x86_64.rpm,xapi-tests-1.110.1-1.2.xcp.x86_64.rpm,xapi-xe-1.110.1-1.2.xcp.x86_64.rpm}
yum update xapi-core-1.110.1-1.2.xcp.x86_64.rpm xapi-tests-1.110.1-1.2.xcp.x86_64.rpm xapi-xe-1.110.1-1.2.xcp.x86_64.rpm
xe-toolstack-restart
```

**Comment by Steve-sibilia** [comment]
Hi, 
I can test the migration of a windows VM, but I'm stuck with the error NOT_SUPPORTED_DURING_UPGRADE() even with your experimental XAPI :(

**Comment by Steve-sibilia** [comment]
To be ore precise the error is:
vm.migrate
{
  "vm": "d664ba36-dca7-8764-2d4b-d1a35438f5b1",
  "sr": "4b128e20-5267-7a75-cfc9-ba6382fe7144",
  "targetHost": "f834d6ee-b0c2-4ada-aa1d-0f1614e9c56c",
  "id": "d664ba36-dca7-8764-2d4b-d1a35438f5b1"
}
{
  "message": "MESSAGE_METHOD_UNKNOWN(VM.assert_can_migrate_sender)",
  "stack": "XapiError: MESSAGE_METHOD_UNKNOWN(VM.assert_can_migrate_sender)
    at wrapError (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:113:9)
    at _call.catch.error (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:1105:18)
    at run (/usr/local/lib/node_modules/xo-server-xoa/node_modules/core-js/modules/es6.promise.js:66:22)
    at /usr/local/lib/node_modules/xo-server-xoa/node_modules/core-js/modules/es6.promise.js:79:30
    at flush (/usr/local/lib/node_modules/xo-server-xoa/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)",
  "code": "MESSAGE_METHOD_UNKNOWN",
  "params": [
    "VM.assert_can_migrate_sender"
  ],
  "call": {
    "method": "VM.migrate_send",
    "params": [
      "OpaqueRef:35173e3f-22ab-4b0f-a9e5-00f32e2b6365",
      "OpaqueRef:323cb85f-4538-aa83-4a3a-35054f57d270",
      {
        "SM": "http://192.168.12.125/services/SM?session_id=OpaqueRef:577f422d-da54-4a32-908a-5ac70c48cbf3",
        "host": "OpaqueRef:6d8ed1c1-ae5e-2f97-01d0-07bbb6fe8233",
        "xenops": "http://192.168.12.125/services/xenops?session_id=OpaqueRef:577f422d-da54-4a32-908a-5ac70c48cbf3",
        "session_id": "OpaqueRef:577f422d-da54-4a32-908a-5ac70c48cbf3",
        "master": "http://192.168.12.125/"
      },
      true,
      {
        "OpaqueRef:1a526336-c16d-423e-2d63-19b27cf29b00": "OpaqueRef:c99401d8-54ad-b500-3d4b-507901851551"
      },
      {},
      {
        "force": "true"
      }
    ]
  }
}

**Comment by stormi** [comment]
Hmm, maybe you need to also update the 7.5 host. I've uploaded XAPI packages for 7.5:

```
wget https://updates.xcp-ng.org/tmp/xapi/7.5/{xapi-core-1.90.6-2.x86_64.rpm,xapi-tests-1.90.6-2.x86_64.rpm,xapi-xe-1.90.6-2.x86_64.rpm}
yum update xapi-core-1.90.6-2.x86_64.rpm  xapi-tests-1.90.6-2.x86_64.rpm  xapi-xe-1.90.6-2.x86_64.rpm
xe-toolstack-restart
```

**Comment by Steve-sibilia** [comment]
Thank you. 
Sadly the other host are xenserver 7.1 :(

**Comment by stormi** [comment]
Since I got no answer on xapi-project/xen-api#3764 I've opened a bug report at xenserver.org:
https://bugs.xenserver.org/browse/XSO-925

**Comment by stormi** [comment]
I have enabled storage migration during pool upgrade in the XAPI in XCP-ng 7.5 and 7.6. Note that it may fail in some cases due to bugs in storage migration in XenServer 7.6 (https://bugs.xenserver.org/browse/XSO-924). But the reason why it was disabled in the first place is not valid anymore so it's better to enable it and fix the remaining issues.

**Comment by stormi** [comment]
Although I still think the reason why it was disabled in the first place is not valid anymore, tests revealed that storage migration during RPU from XenServer 7.2 to XCP-ng (or XenServer) 7.6 will fail because the newer hosts tries to call `assert_can_migrate_sender` from the older host, which doesn't exist in XAPI prior to v1.58.0.

I'm reopening until we find a way to fix that.

**Comment by stormi** [comment]
There's a patch in upstream master for that `assert_can_migrate_sender` issue actually!
https://github.com/xapi-project/xen-api/commit/40fa06915a4fbc1d13ca423a4831c817615d3768

**Comment by stormi** [comment]
I have pushed patched XAPI packages to the `updates_testing` repos for XCP-ng 7.5 and 7.6.

I won't make that an official update unless we can test it enough.

Tests that would need to be done:
* Upgrade a XS 6.5 pool with VMs on local storage towards XCP-ng 7.5 or 7.6 (7.5 might be easier due to remaining bugs in migration from lower versions to 7.6, possibly https://bugs.xenserver.org/browse/XSO-938 for example). Check that the live migration with local storage, that was previously impossible due to the `assert_can_migrate_sender` error, now works. Or report any new error that shows up in the logs if it fails.
* Same test with a more recent XS pool, such as 7.0, 7.1 or 7.2 (but not 7.3 or above) migrated to XCP-ng 7.5 or 7.6.

Those are long tests to do so I'm not going to do it in the next days.

**Comment by stormi** [comment]
I have pushed the update to XCP-ng 7.6, and XCP-ng 8.0 also has the change. This means that you can migrate with storage during a pool upgrade from 7.6 to 8.0 now. My testing was successful, but I could not test every case. It's a difficult test that involves putting a pool temporarily in an heterogenous state (master upgrade, slave not upgraded yet...).
